### ISSUE TITLE
$(AR) not defined

### ISSUE THREAD

**Issue by mrinalsardar** [rnburn/satyr#2]
https://github.com/rnburn/satyr/blob/3583c5e639f55f1554b9e9240f169d7cb7ad1851/bazel/tbb.BUILD#L10

I am trying to build `tensorflow` for my `mac` from source and it uses this library.

Getting the following error:

    ERROR: /private/var/tmp/_bazel_sardarmrinal/841c8c9a203505f6ff7b50ea63697e9e/external/tbb/BUILD.bazel:12:1: in cmd attribute of genrule rule @tbb//:build_tbb: $(AR) not defined

**Comment by rnburn** [comment]
Fixed in #3
